name: Build Test

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: ls # write Build Test Command(Find GitHub-Actions)
